audit_header: false
title: "Chicago's Best Real Estate Training"
description: Amy Kite, a top Real Estate Agent in Chicago, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Amy Kite
  title:
  license_number:
  about_markdown: |
    When people ask Amy Kite what she does for a living, she replies, “I help individuals build their future and create their legacy by investing in real estate." Amy can not think of a better way to spend her day! There is no greater joy to her than when she sees a satisfied and excited client to start a grand new chapter in their life.

    It's no wonder that Amy is now considered a Top Expert in her area. She has netted 98.7% for her clients of their asking price for the past 3 years.  For 2007, she has netted 99.5% for her sellers of their asking price and her buyers have paid on average 92% of the asking price. As you could imagine, her clients are extremely grateful and are very satisfied!
  market: Chicago
  brand: The Kite Team
  brokerage: Keller Williams Realty Infinity
  address: 501 Peterson Rd, Suite 200<br>Libertyville, IL 60048
  phone: 847-877-9881
  phone_type:
  phone2:
  phone2_type:
  email: amy@amykite.com
  url: http://www.amykite.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KiteTeamRealEstate
  linkedin_url: https://www.linkedin.com/in/amykite
  youtube_url: https://www.youtube.com/channel/UCce-kFCFi8JEl4EhjHznCMQ
  twitter_url: https://twitter.com/TheKiteTeamKW
  instagram_url: https://www.instagram.com/thekiteteamkwrealty/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b21f24'
  theme_color: '#65696e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
